### ISSUE TITLE
Limit output on cli

### ISSUE THREAD

**Issue by phlegx** [hashicorp/terraform-provider-http#188]
### Terraform CLI and Provider Versions

Terraform version 1.0.11

### Use Cases or Problem Statement

The ouptut of the plugin, depending on what you fetch, can be huge and makes every apply very tedious.

### Proposal

Could we either have a flag that limits this output to a few lines maybe or even better, show only the changes? Otherwise every apply needs to be scrolled and that makes it very .

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bflad** [comment]
Hi @phlegx 👋 Thank you for raising this.

To better help you, I think we may need to understand a little more about _what_ output you are seeing and _how_ you are executing Terraform. If you can provide this information, we can point you in a better direction. The output of a Terraform command is generally controlled by [Terraform CLI](https://github.com/hashicorp/terraform) itself, rather than providers, unless something is unexpectedly not working with provider logging.

**Comment by phlegx** [comment]
hi @bflad!

For example I have this data provider, fetching me a list of all atlassian/bitbucket IP's::

```
data "http" "bitbucket_ips" {
  url = "https://ip-ranges.atlassian.com/"
  request_headers = {
    Accept = "application/json"
  }
}
```

When code was applied, we had a huge output with terraform `1.0.11`. I was now trying to reproduce this to give you an example. We just yesterday updated to terraform `1.2.9` but the issue is now gone. No more huge output. I guess this was solved with new Terraforn.

Sorry for the confusion
