### ISSUE TITLE
Allow XML Content-Type

### ISSUE THREAD

**Issue by jeremymcgee73** [hashicorp/terraform-provider-http#99]
Hello,
I believe the issue is that XML content type is not allowed in the return.

### Terraform Version
Terraform v0.14.9

### Affected Resource(s)
- data.http

### Terraform Configuration Files
```hcl
data "http" "what_xml" {
  url = "https://whatever.com/file.xml"
  # Optional request headers
  request_headers = {
    Accept = "application/xml"
  }
}
```

### Debug Output
```
Warning: Content-Type is not recognized as a text type, got "application/xml;charset=UTF-8"

  on keycloak.tf line 24, in data "http" "what_xml":
  24: data "http" "what_xml" {

If the content is binary data, Terraform may not properly handle the contents
of the response.
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The HTTP request should be saved into the body.

### Actual Behavior
An error occured.

**Comment by jeremymcgee73** [comment]
Thanks so much! Do you think we could get a new release for this?

Thanks!

**Comment by dracut5** [comment]
Faced with the same issue. I see the fix is already merged, would be great to have a new release.

Thank you!

**Comment by bendbennett** [comment]
@jeremymcgee73 @dracut5 it seems that content-types that are not recognised as text have been "allowed" since [v2.0.0](https://github.com/hashicorp/terraform-provider-http/releases/tag/v2.0.0) in that if the content-type is not identified as text then a warning is issued but the `body` (or `response_body` since [v2.2.0](https://github.com/hashicorp/terraform-provider-http/releases/tag/v2.2.0)) should still be populated with a string representation of the response body.
